{% set version = '0.6-26' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-misctools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/miscTools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/miscTools/miscTools_{{ version }}.tar.gz
  sha256: be3c5a63ca12ce7ce4d43767a1815cd3dcf32664728ade251cfb03ea6f77fc9a

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-digest
  run:
    - r-base
    - r-digest

test:
  commands:
    - $R -e "library('miscTools')"           # [not win]
    - "\"%R%\" -e \"library('miscTools')\""  # [win]

about:
  home: http://www.micEcon.org
  license: GPL-2
  summary: Miscellaneous small tools and utilities. Many of them facilitate the work with matrices,
    e.g. inserting rows or columns, creating symmetric matrices, or checking for semidefiniteness.
    Other tools facilitate the work with regression models, e.g. extracting the standard
    errors, obtaining the number of (estimated) parameters, or calculating R-squared
    values.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: miscTools
# Version: 0.6-26
# Date: 2019-12-08
# Title: Miscellaneous Tools and Utilities
# Author: Arne Henningsen, Ott Toomet
# Maintainer: Arne Henningsen <arne.henningsen@gmail.com>
# Depends: R (>= 2.14.0)
# Imports: digest
# Suggests: Ecdat (>= 0.1-5)
# Description: Miscellaneous small tools and utilities. Many of them facilitate the work with matrices, e.g. inserting rows or columns, creating symmetric matrices, or checking for semidefiniteness. Other tools facilitate the work with regression models, e.g. extracting the standard errors, obtaining the number of (estimated) parameters, or calculating R-squared values.
# License: GPL (>= 2)
# URL: http://www.micEcon.org
# NeedsCompilation: no
# Packaged: 2019-12-08 08:37:45 UTC; gsl324
# Repository: CRAN
# Date/Publication: 2019-12-08 09:10:03 UTC
