appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: URltFKP6NTfbZwZWPOF/S7edjEQT5AJkTRHAtrDultppVJP31IXMAv/WyDAgnZeRjDsOBjC4BzRi9uvFUkqFxyNYfCaEac2jVyzKQKzwfNLLdQsQj2ejbx38rXxPaKn1Pd7NgTpGLE6Nquri6tsi4YkdeKci/BWqgpv8TNxZa4iWO8s0t8kvvvP4feru1VgB9/nRJnxbEQybdwfNTJdCxX+RLUGlAFFMhRFceTmRkjkaMlUDWtS/fTTg5higFoTcS8UNkNme7OYdNvrf0HLhxH8Z7wY4d/iZ7eiNg0DPqBJno83NcM26ZxR0XQxwu0PmOdv5cXWJ3sLwyp6PRyJAo2cr0QwGvlhgeHbqRVLtQNCf3xNcBRlQtPuOeshlZ39tWK2RjRtXOUkgUsudHdnAaL7TobfQrfQjlE2mCxPewjFRYIfTR0GBjmYbRzP1SVi2FpOALqrz0AEHd4hurkVmHEsU3tBQ4bCUObZkBtbeBRnb4b7vKhlGRjEu83vmNrhJWK3J5GR9h9gaoV2VFZ5oNFIt9A5ksPAPiTqo80UtUSpDNiVbi6fxfRdx9xIMDRM3IpBbNGhs2B9fO2jdTiIUjGqT8AMlZtkNEXCl0mjtrV8TW78ew0wFRoUicYfCzISJjgha5IPrLNYOzEsvY99j/k/GEjAubqKzr7U5qjPv9R8=}
