travis:
  secure:
    BINSTAR_TOKEN: Z3c8FZ+5Y2tUYPh8lYFN2MMC6YybEGeBwiusE5xvq46oOny+PC9HBE08P0xw0dFoIJJ3eukH9uJPij4etCHZyGqkOYHH4Ch5MLUnvPhCmfU1JER26uk7zRaEi9PjbVk1rGXu7ljti14hccWPlywx8Ucn+NQ/KjruCEEhBOawaLBIEpOKT4KKTWGO5UqHC3EQ68cVE+/EHB2rq4w6iis1lPQtyCh22+d/d4diVwCZnDuUu33ZfImdvFW3ruKfPFO0wBqTT7sgMX8+UsQ47DDTNYhLOXcWr57zY2QEaJig8ATvuzX3f5Q6tmjMvaXhB+glhPiYkKhbbiEL1u99pfLSShMow0eLeu5h2a0rxhEt3U08VzNtmtPuUj9lGAS/BqJ5R9DeOMI8Fz7ih4NQaGVDncQvLYkuvMhJvEgGULY64WwIuwAfP60wG0YMBLuw2+K93gH9LP+Z50Yf+BLIaw4vP/PU6zEr8MpDBKGA0GoUd3VNHcyPqJTd/k/+3Zj9rQjaCDXVsS7AQhF9C6N1+1ZrVPm9ta0Krr4uAPtFl69LGv+gn0KfWV0qMJfyUOkE1Psjcyg7oSDqHbBdxjvfd1iVfaHphxt8O9RACKQ3oFznCYNqon6zzN+8xozKflC3aw2MTVkMWEHl3OsWdIfNd3tjQGeb8MKO/IiiJtvCCO0T6SU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
